// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcJe3vHCfxSiataIwcd458xhWsdKz_IM4',
    appId: '1:259004174978:web:55d0f58a73eba3a5ee1a9b',
    messagingSenderId: '259004174978',
    projectId: 'baochay2-3f8c0',
    authDomain: 'baochay2-3f8c0.firebaseapp.com',
    databaseURL: 'https://baochay2-3f8c0-default-rtdb.firebaseio.com',
    storageBucket: 'baochay2-3f8c0.appspot.com',
    measurementId: 'G-C7KRGTLT95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFqWcQktMdSzXpl7RflQbEmWVOcyDQPBw',
    appId: '1:259004174978:android:3fa9221d8edd0126ee1a9b',
    messagingSenderId: '259004174978',
    projectId: 'baochay2-3f8c0',
    databaseURL: 'https://baochay2-3f8c0-default-rtdb.firebaseio.com',
    storageBucket: 'baochay2-3f8c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd5bLIPUtaetOihaNhByceqpsx6tK5TJM',
    appId: '1:259004174978:ios:c9604206d3af8237ee1a9b',
    messagingSenderId: '259004174978',
    projectId: 'baochay2-3f8c0',
    databaseURL: 'https://baochay2-3f8c0-default-rtdb.firebaseio.com',
    storageBucket: 'baochay2-3f8c0.appspot.com',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd5bLIPUtaetOihaNhByceqpsx6tK5TJM',
    appId: '1:259004174978:ios:c9604206d3af8237ee1a9b',
    messagingSenderId: '259004174978',
    projectId: 'baochay2-3f8c0',
    databaseURL: 'https://baochay2-3f8c0-default-rtdb.firebaseio.com',
    storageBucket: 'baochay2-3f8c0.appspot.com',
    iosBundleId: 'com.example.app2',
  );
}
